services:

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=chatdb
      - POSTGRES_USER=chatuser
      - POSTGRES_PASSWORD=chatpassword
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  chat-app:
    build: .
    image: chat-app
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_NAME=chatdb
      - DB_USER=chatuser
      - DB_PASSWORD=chatpassword
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  db_data: