services:

  redis:
    image: redis:7-alpine
    container_name: redis_server
    ports:
      - "6379:6379"

  chat-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    image: chat-image
    container_name: chat
    depends_on:
      - redis