# Generated by Django 5.2 on 2025-05-26 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_room_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='owner',
        ),
    ]
