# Generated by Django 5.2 on 2025-06-02 23:39

import app.utils.extra_functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_room_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, default=app.utils.extra_functions.sao_paulo_now, null=True),
        ),
    ]
