# Generated by Django 5.2 on 2025-06-12 00:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_user_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image_profile",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image_profile"
            ),
        ),
    ]
